### ISSUE TITLE
clone_wp_site.py: Database config not updated properly

### ISSUE THREAD

**Issue by cvn** [opalstack/opalstack-python#8]
clone_wp_site.py does not update the cloned wp-config to point to the dst database. And so the dst app unintentionally reads and writes to the src database.

This means that when the script updates the `siteurl` and `home` options through the wp-cli tool, it modifies the src database, even though it's intended for the dst app.

https://github.com/opalstack/opalstack-python/blob/13642f1e74de74daa38e8c5ed97cfe432494eeee/examples/clone_wp_site.py#L159-L161

So you end up with the src app redirecting to the dst domain, which is serving the dst app, but is still using the src database.

**Comment by yqdv** [comment]
This was quite a serious bug. Sincere apologies for oversight and trouble it caused.
I've tested and applied your fix. Will soon release a 1.0.1 version which includes this fix.
